/*
  Warnings:

  - You are about to drop the `Post` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `User` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "Post";
PRAGMA foreign_keys=on;

-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "User";
PRAGMA foreign_keys=on;

-- CreateTable
CREATE TABLE "USER" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "ROLE" TEXT NOT NULL DEFAULT 'user',
    "IS_VERIFIED" BOOLEAN NOT NULL DEFAULT false,
    "VERIFY_CODE" TEXT,
    "VERIFY_CODE_EXPIRES" DATETIME,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "POST" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "TITLE" TEXT NOT NULL,
    "CONTENT" TEXT NOT NULL,
    "AUTHOR_ID" INTEGER NOT NULL,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "POST_AUTHOR_ID_fkey" FOREIGN KEY ("AUTHOR_ID") REFERENCES "USER" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TASK" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "TITLE" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" TEXT NOT NULL DEFAULT 'todo',
    "PRIORITY" TEXT NOT NULL DEFAULT 'normal',
    "DUE_DATE" DATETIME,
    "CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" DATETIME NOT NULL,
    "USER_ID" INTEGER,
    CONSTRAINT "TASK_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_EMAIL_key" ON "USER"("EMAIL");
